#!/usr/bin/env bash

set -euo pipefail

pman_u_name="package-man-u"
pman_u_url="https://raw.githubusercontent.com/c-MatMaka-r/$pman_u_name/main/$pman_u_name"
pman_u_dest="/usr/local/bin"

# if not root do nothing
if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required."
  exit 1
fi

if ! command -v $pman_u_name > /dev/null 2>&1
then
  echo "$pman_u_name isn't installed."
  echo "Installation..."
  cd "$pman_u_dest"
  curl -O "$pman_u_url"
  
  chmod +x "$pman_u_dest/$pman_u_name"
  echo "Installed."
fi

"$pman_u_dest/$pman_u_name"
